kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  schema-registry-url: ${SCHEMA_REGISTRY_URL:http://90.156.226.5:8081}
  consumers:
    common:
      auto-offset-reset: earliest
      auto-commit: true
    json:
      topic: clicks.incoming
      group-id: clicks.incoming.json.group
  producers:
    json:
      topic: clicks.incoming

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/analytics_db
    username: postgres
    password: postgres


server:
  port: 8080