-- liquibase formatted sql
-- changeset admin:1

CREATE TABLE analytics.clicks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    page INT NOT NULL,
    clicked_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_clicks_clicked_at ON analytics.clicks (clicked_at);